### ISSUE TITLE
Remove Medium Link from Footer

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#9]
Initially we planned on cross-posting to Medium as well.

Because of various reasons (mostly Mediums annoying force to sign up UX and poor work:benefit ratio) we will pause that for now however and stay focused on Gatsby.
If we ever want to revisit this decision we can, the medium handle is blocked.

Therefore we should remove the medium link from the footer.

**Comment by JackKelly** [comment]
Is Medium definitely the best choice for our blogging platform?  

I certainly can't claim to have done any rigorous research on the topic!  I only ask because I've heard people grumble about Medium recently (mostly, I think, because Medium nags users to sign in).

I've been quite happy with Jekyll.  But I appreciate that it's perhaps not the easiest-to-use platform; and that Medium might help us to get more readers.

**Comment by flowirtz** [comment]
@JackKelly totally forgot to get back to you.

Medium is definitely **not** the best choice, imo! I keep getting bothered by it to sign up for an account, the endless popup is really not improving the UX for me.
I only thought of it because it feels like the default for blog posts nowadays. Also, it might be a good way to increase reach.

I'd always keep the blog posts here, hosted via GitHub & Gatsby. We could import our posts into medium however, they parse the markdown as well and it would link back to our website.
For now probably a lot of work for a small gain though.

I think I'll remove the medium link from the footer for now, as it's already pretty cluttered and we are not using it. Maybe one day we make use of it, the medium username is blocked by me. 😊

**Comment by JackKelly** [comment]
Cool, sounds good to me!
